/**
 * Publication Module
 *
 * Export and publish RCM collections, Things, and annotations.
 * Supports JSON-LD export, static HTML generation, and LDN announcement.
 */

import type { CoreEntity, Annotation, Collection } from "../core/types";
import type { ChonkyNode } from "../graph/types";
import type { LdnAnnouncement } from "../storage/types";
import { createCollectionAnnouncement, createThingAnnouncement } from "../storage/ldn";

/**
 * Export format options.
 */
export type ExportFormat = "jsonld" | "json" | "html" | "turtle" | "ntriples";

/**
 * Export options.
 */
export interface ExportOptions {
  /** Desired format. */
  format: ExportFormat;
  /** Whether to include @context. */
  includeContext?: boolean;
  /** Whether to include provenance. */
  includeProvenance?: boolean;
  /** Whether to include machine annotations. */
  includeMachineAnnotations?: boolean;
  /** Pretty-print output. */
  pretty?: boolean;
}

/**
 * Export a single entity as JSON-LD.
 */
export function exportEntity(entity: CoreEntity, options: ExportOptions = { format: "jsonld" }): string {
  const obj: Record<string, unknown> = { ...entity };

  if (options.includeContext ?? true) {
    obj["@context"] = "./schemas/rcm-context.jsonld";
  }

  if (!options.includeProvenance) {
    delete obj["dcterms:creator"];
    delete obj["dcterms:created"];
    delete obj["dcterms:modified"];
  }

  const indent = options.pretty ? 2 : undefined;
  return JSON.stringify(obj, null, indent);
}

/**
 * Export a chonky node as a complete JSON-LD bundle.
 */
export function exportChonkyNode(node: ChonkyNode, options: ExportOptions = { format: "jsonld" }): string {
  const graph: CoreEntity[] = [node.thing];

  if (options.includeMachineAnnotations ?? true) {
    graph.push(...node.annotations as unknown as CoreEntity[]);
  } else {
    graph.push(...node.humanAnnotations as unknown as CoreEntity[]);
  }

  const bundle = {
    "@context": options.includeContext ? "./schemas/rcm-context.jsonld" : undefined,
    "@graph": graph,
  };

  const indent = options.pretty ? 2 : undefined;
  return JSON.stringify(bundle, null, indent);
}

/**
 * Export a collection as a JSON-LD bundle.
 */
export function exportCollection(
  collection: Collection,
  members: CoreEntity[],
  options: ExportOptions = { format: "jsonld" },
): string {
  const graph = [collection, ...members];

  const bundle = {
    "@context": options.includeContext ? "./schemas/rcm-context.jsonld" : undefined,
    "@graph": graph,
  };

  const indent = options.pretty ? 2 : undefined;
  return JSON.stringify(bundle, null, indent);
}

/**
 * Generate a static HTML page for a chonky node.
 */
export function generateStaticHtml(node: ChonkyNode, title?: string): string {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title ?? String(node.thing["rdfs:label"] ?? node.thing["@id"]))}</title>
  <script type="application/ld+json">
  ${exportChonkyNode(node, { pretty: true })}
  </script>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }
    h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
    .assertion { margin: 1rem 0; padding: 0.5rem; background: #f5f5f5; border-radius: 4px; }
    .machine { background: #fff3cd; }
    .dispute { background: #f8d7da; }
    cite { font-style: italic; color: #666; }
  </style>
</head>
<body>
  <h1>${escapeHtml(String(node.thing["rdfs:label"] ?? node.thing["@id"]))}</h1>
  <p class="id">${escapeHtml(node.thing["@id"])}</p>
  <p class="type">${escapeHtml(String(node.thing["@type"]))}</p>

  <h2>Assertions (${node.humanAnnotations.length})</h2>
  ${node.humanAnnotations.map((a) => `
    <div class="assertion">
      <p>${escapeHtml(JSON.stringify(a["oa:hasBody"]))}</p>
      <cite>by ${escapeHtml(a["dcterms:creator"] ?? "unknown")}, ${escapeHtml(a["dcterms:created"] ?? "")}</cite>
    </div>
  `).join("")}

  ${node.machineAnnotations.length > 0 ? `
    <h2>Machine Suggestions (${node.machineAnnotations.length})</h2>
    ${node.machineAnnotations.map((a) => `
      <div class="assertion machine">
        <p>${escapeHtml(JSON.stringify(a["oa:hasBody"]))}</p>
      </div>
    `).join("")}
  ` : ""}

  ${node.disputes.length > 0 ? `
    <h2>Disputed Assertions (${node.disputes.length})</h2>
    ${node.disputes.map((a) => `
      <div class="assertion dispute">
        <p>${escapeHtml(JSON.stringify(a["oa:hasBody"]))}</p>
      </div>
    `).join("")}
  ` : ""}

  <footer>
    <p>Generated by RERUM Collection Management on ${new Date().toISOString()}</p>
  </footer>
</body>
</html>`;

  return html;
}

/**
 * Create an LDN announcement for publishing a chonky node.
 */
export function announceChonkyNode(
  node: ChonkyNode,
  actorId: string,
  inboxUrl: string,
): LdnAnnouncement {
  return createThingAnnouncement(
    actorId,
    node.thing["@id"],
    inboxUrl,
    `Published: ${node.thing["rdfs:label"] ?? node.thing["@id"]} (${node.annotations.length} annotations)`,
  );
}

/**
 * Create an LDN announcement for publishing a collection.
 */
export function announceCollection(
  collection: Collection,
  actorId: string,
  inboxUrl: string,
  memberCount: number,
): LdnAnnouncement {
  return createCollectionAnnouncement(
    actorId,
    collection["@id"],
    inboxUrl,
    `Published collection: ${collection["rdfs:label"] ?? collection["@id"]} (${memberCount} members)`,
  );
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
